name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*'       # Trigger workflow on semantic version tags (e.g., v1.0.0, v2.3.4)
    branches:
      - main  # Trigger on pushes to the 'main' branch
  workflow_dispatch: # Allow manual triggering of the workflow
env:
  IMAGE_NAME: orthanc-auth-service  # Define custom image name here
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      packages: write # Required to publish to GitHub Packages
      contents: read  # Allows access to repository contents

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Extract version from tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "IMAGE_TAG=${GITHUB_REF##refs/tags/}" >> $GITHUB_ENV

    - name: Set 'latest' tag for main branch
      if: github.ref == 'refs/heads/main'
      run: echo "IMAGE_TAG=latest" >> $GITHUB_ENV

    - name: Log in to GitHub Docker Registry
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} . \
        --label "org.opencontainers.image.source=https://github.com/digihunchinc/orthanc_auth_service" \
        --label "org.opencontainers.image.description=Orthanc Custom Authorization Web Service" \
        --label "org.opencontainers.image.licenses=MIT"

    - name: Push Docker image to GitHub Packages
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

